// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void animGridJump_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_pnlSolar1;
lv_obj_t * ui_ImgEvcc;
lv_obj_t * ui_barHomeBattery;
lv_obj_t * ui_ImgBattery;
lv_obj_t * ui_barBatteryPower;
lv_obj_t * ui_spinLadung;
lv_obj_t * ui_ImgPlug;
lv_obj_t * ui_lblLadepunkt;
lv_obj_t * ui_lblLadeleistung;
lv_obj_t * ui_txtLadeleistung;
lv_obj_t * ui_pnlCarSoc;
lv_obj_t * ui_txtLadestand;
lv_obj_t * ui_lblAuto;
lv_obj_t * ui_barCarSoc;
void ui_event_sliderSocLimit(lv_event_t * e);
lv_obj_t * ui_sliderSocLimit;
lv_obj_t * ui_lblReichweite;
lv_obj_t * ui_txtReichweite;
lv_obj_t * ui_lblRestzeit;
lv_obj_t * ui_txtRestzeit;
lv_obj_t * ui_lblLadeenergie;
lv_obj_t * ui_txtLadeenergie;
lv_obj_t * ui_lblLadelimit;
lv_obj_t * ui_txtLadelimit;
void ui_event_BtnModusPv(lv_event_t * e);
lv_obj_t * ui_BtnModusPv;
lv_obj_t * ui_txtBtnModusPv;
void ui_event_BtnModusPlan(lv_event_t * e);
lv_obj_t * ui_BtnModusPlan;
lv_obj_t * ui_txtBtnModusPlan;
void ui_event_BtnModusNow(lv_event_t * e);
lv_obj_t * ui_BtnModusNow;
lv_obj_t * ui_txtBtnModusNow;
lv_obj_t * ui_pnlSolar;
lv_obj_t * ui_barSolarGrid;
lv_obj_t * ui_barSolarPower;
lv_obj_t * ui_ImgSolar;
lv_obj_t * ui_ImgGrid;
lv_obj_t * ui_barGridPower;
lv_obj_t * ui_pnlDark;
lv_obj_t * ui_lblWifiWait;
lv_obj_t * ui_lblMqttWait;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1739134342[1] = {&ui_img_1529214255};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void animGridJump_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 310, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 10);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_sliderSocLimit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_txtLadelimit, target, "", "%");
    }
    if(event_code == LV_EVENT_RELEASED) {
        sendEvccLimitSoc(e);
    }
}
void ui_event_BtnModusPv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        sendEvccModePV(e);
    }
}
void ui_event_BtnModusPlan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        sendEvccPlan(e);
    }
}
void ui_event_BtnModusNow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        sendEvccModeNow(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
