// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void animGridJump_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_pnlSolar1;
extern lv_obj_t * ui_ImgEvcc;
extern lv_obj_t * ui_barHomeBattery;
extern lv_obj_t * ui_ImgBattery;
extern lv_obj_t * ui_barBatteryPower;
extern lv_obj_t * ui_spinLadung;
extern lv_obj_t * ui_ImgPlug;
extern lv_obj_t * ui_lblLadepunkt;
extern lv_obj_t * ui_lblLadeleistung;
extern lv_obj_t * ui_txtLadeleistung;
extern lv_obj_t * ui_pnlCarSoc;
extern lv_obj_t * ui_txtLadestand;
extern lv_obj_t * ui_lblAuto;
extern lv_obj_t * ui_barCarSoc;
void ui_event_sliderSocLimit(lv_event_t * e);
extern lv_obj_t * ui_sliderSocLimit;
extern lv_obj_t * ui_lblReichweite;
extern lv_obj_t * ui_txtReichweite;
extern lv_obj_t * ui_lblRestzeit;
extern lv_obj_t * ui_txtRestzeit;
extern lv_obj_t * ui_lblLadeenergie;
extern lv_obj_t * ui_txtLadeenergie;
extern lv_obj_t * ui_lblLadelimit;
extern lv_obj_t * ui_txtLadelimit;
void ui_event_BtnModusPv(lv_event_t * e);
extern lv_obj_t * ui_BtnModusPv;
extern lv_obj_t * ui_txtBtnModusPv;
void ui_event_BtnModusPlan(lv_event_t * e);
extern lv_obj_t * ui_BtnModusPlan;
extern lv_obj_t * ui_txtBtnModusPlan;
void ui_event_BtnModusNow(lv_event_t * e);
extern lv_obj_t * ui_BtnModusNow;
extern lv_obj_t * ui_txtBtnModusNow;
extern lv_obj_t * ui_pnlSolar;
extern lv_obj_t * ui_barSolarGrid;
extern lv_obj_t * ui_barSolarPower;
extern lv_obj_t * ui_ImgSolar;
extern lv_obj_t * ui_ImgGrid;
extern lv_obj_t * ui_barGridPower;
extern lv_obj_t * ui_pnlDark;
extern lv_obj_t * ui_lblWifiWait;
extern lv_obj_t * ui_lblMqttWait;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_evcc_logo_png);    // assets/evcc_logo.png
LV_IMG_DECLARE(ui_img_1529214255);    // assets/battery-2.png
LV_IMG_DECLARE(ui_img_955610505);    // assets/ev-charging-plug-icon.png
LV_IMG_DECLARE(ui_img_9025960_sun_icon_png);    // assets/9025960_sun_icon.png
LV_IMG_DECLARE(ui_img_1680447448);    // assets/electrical-tower-svgrepo-com.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
